// source: jdocs.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.jdocspb.Jdoc');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jdocspb.Jdoc = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jdocspb.Jdoc, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jdocspb.Jdoc.displayName = 'proto.jdocspb.Jdoc';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jdocspb.Jdoc.prototype.toObject = function(opt_includeInstance) {
  return proto.jdocspb.Jdoc.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jdocspb.Jdoc} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdocspb.Jdoc.toObject = function(includeInstance, msg) {
  var f, obj = {
    docVersion: jspb.Message.getFieldWithDefault(msg, 1, 0),
    fmtVersion: jspb.Message.getFieldWithDefault(msg, 2, 0),
    clientMetadata: jspb.Message.getFieldWithDefault(msg, 3, ""),
    jsonDoc: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jdocspb.Jdoc}
 */
proto.jdocspb.Jdoc.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jdocspb.Jdoc;
  return proto.jdocspb.Jdoc.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jdocspb.Jdoc} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jdocspb.Jdoc}
 */
proto.jdocspb.Jdoc.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDocVersion(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setFmtVersion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientMetadata(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setJsonDoc(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jdocspb.Jdoc.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jdocspb.Jdoc.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jdocspb.Jdoc} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdocspb.Jdoc.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDocVersion();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getFmtVersion();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getClientMetadata();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getJsonDoc();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional uint64 doc_version = 1;
 * @return {number}
 */
proto.jdocspb.Jdoc.prototype.getDocVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdocspb.Jdoc} returns this
 */
proto.jdocspb.Jdoc.prototype.setDocVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint64 fmt_version = 2;
 * @return {number}
 */
proto.jdocspb.Jdoc.prototype.getFmtVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdocspb.Jdoc} returns this
 */
proto.jdocspb.Jdoc.prototype.setFmtVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string client_metadata = 3;
 * @return {string}
 */
proto.jdocspb.Jdoc.prototype.getClientMetadata = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdocspb.Jdoc} returns this
 */
proto.jdocspb.Jdoc.prototype.setClientMetadata = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string json_doc = 4;
 * @return {string}
 */
proto.jdocspb.Jdoc.prototype.getJsonDoc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdocspb.Jdoc} returns this
 */
proto.jdocspb.Jdoc.prototype.setJsonDoc = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


