// source: jdocs.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.jdocspb.ReadDocsResp');
goog.provide('proto.jdocspb.ReadDocsResp.Item');
goog.provide('proto.jdocspb.ReadDocsResp.Status');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.jdocspb.Jdoc');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jdocspb.ReadDocsResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jdocspb.ReadDocsResp.repeatedFields_, null);
};
goog.inherits(proto.jdocspb.ReadDocsResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jdocspb.ReadDocsResp.displayName = 'proto.jdocspb.ReadDocsResp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jdocspb.ReadDocsResp.Item = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jdocspb.ReadDocsResp.Item, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jdocspb.ReadDocsResp.Item.displayName = 'proto.jdocspb.ReadDocsResp.Item';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jdocspb.ReadDocsResp.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jdocspb.ReadDocsResp.prototype.toObject = function(opt_includeInstance) {
  return proto.jdocspb.ReadDocsResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jdocspb.ReadDocsResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdocspb.ReadDocsResp.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.jdocspb.ReadDocsResp.Item.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jdocspb.ReadDocsResp}
 */
proto.jdocspb.ReadDocsResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jdocspb.ReadDocsResp;
  return proto.jdocspb.ReadDocsResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jdocspb.ReadDocsResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jdocspb.ReadDocsResp}
 */
proto.jdocspb.ReadDocsResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.jdocspb.ReadDocsResp.Item;
      reader.readMessage(value,proto.jdocspb.ReadDocsResp.Item.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jdocspb.ReadDocsResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jdocspb.ReadDocsResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jdocspb.ReadDocsResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdocspb.ReadDocsResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.jdocspb.ReadDocsResp.Item.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.jdocspb.ReadDocsResp.Status = {
  UNCHANGED: 0,
  CHANGED: 1,
  NOT_FOUND: 2
};




if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jdocspb.ReadDocsResp.Item.prototype.toObject = function(opt_includeInstance) {
  return proto.jdocspb.ReadDocsResp.Item.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jdocspb.ReadDocsResp.Item} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdocspb.ReadDocsResp.Item.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getFieldWithDefault(msg, 1, 0),
    doc: (f = msg.getDoc()) && proto.jdocspb.Jdoc.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jdocspb.ReadDocsResp.Item}
 */
proto.jdocspb.ReadDocsResp.Item.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jdocspb.ReadDocsResp.Item;
  return proto.jdocspb.ReadDocsResp.Item.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jdocspb.ReadDocsResp.Item} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jdocspb.ReadDocsResp.Item}
 */
proto.jdocspb.ReadDocsResp.Item.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.jdocspb.ReadDocsResp.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 2:
      var value = new proto.jdocspb.Jdoc;
      reader.readMessage(value,proto.jdocspb.Jdoc.deserializeBinaryFromReader);
      msg.setDoc(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jdocspb.ReadDocsResp.Item.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jdocspb.ReadDocsResp.Item.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jdocspb.ReadDocsResp.Item} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdocspb.ReadDocsResp.Item.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getDoc();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.jdocspb.Jdoc.serializeBinaryToWriter
    );
  }
};


/**
 * optional Status status = 1;
 * @return {!proto.jdocspb.ReadDocsResp.Status}
 */
proto.jdocspb.ReadDocsResp.Item.prototype.getStatus = function() {
  return /** @type {!proto.jdocspb.ReadDocsResp.Status} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.jdocspb.ReadDocsResp.Status} value
 * @return {!proto.jdocspb.ReadDocsResp.Item} returns this
 */
proto.jdocspb.ReadDocsResp.Item.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Jdoc doc = 2;
 * @return {?proto.jdocspb.Jdoc}
 */
proto.jdocspb.ReadDocsResp.Item.prototype.getDoc = function() {
  return /** @type{?proto.jdocspb.Jdoc} */ (
    jspb.Message.getWrapperField(this, proto.jdocspb.Jdoc, 2));
};


/**
 * @param {?proto.jdocspb.Jdoc|undefined} value
 * @return {!proto.jdocspb.ReadDocsResp.Item} returns this
*/
proto.jdocspb.ReadDocsResp.Item.prototype.setDoc = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jdocspb.ReadDocsResp.Item} returns this
 */
proto.jdocspb.ReadDocsResp.Item.prototype.clearDoc = function() {
  return this.setDoc(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jdocspb.ReadDocsResp.Item.prototype.hasDoc = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated Item items = 1;
 * @return {!Array<!proto.jdocspb.ReadDocsResp.Item>}
 */
proto.jdocspb.ReadDocsResp.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.jdocspb.ReadDocsResp.Item>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jdocspb.ReadDocsResp.Item, 1));
};


/**
 * @param {!Array<!proto.jdocspb.ReadDocsResp.Item>} value
 * @return {!proto.jdocspb.ReadDocsResp} returns this
*/
proto.jdocspb.ReadDocsResp.prototype.setItemsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.jdocspb.ReadDocsResp.Item=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jdocspb.ReadDocsResp.Item}
 */
proto.jdocspb.ReadDocsResp.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.jdocspb.ReadDocsResp.Item, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jdocspb.ReadDocsResp} returns this
 */
proto.jdocspb.ReadDocsResp.prototype.clearItemsList = function() {
  return this.setItemsList([]);
};


