// source: chipperpb.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.chippergrpc2.IntentGraphResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.chippergrpc2.IntentResult');
goog.require('proto.chippergrpc2.SpeechResult');

goog.forwardDeclare('proto.chippergrpc2.IntentGraphMode');
goog.forwardDeclare('proto.chippergrpc2.RobotMode');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.chippergrpc2.IntentGraphResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.chippergrpc2.IntentGraphResponse.repeatedFields_, null);
};
goog.inherits(proto.chippergrpc2.IntentGraphResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.chippergrpc2.IntentGraphResponse.displayName = 'proto.chippergrpc2.IntentGraphResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.chippergrpc2.IntentGraphResponse.repeatedFields_ = [11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.chippergrpc2.IntentGraphResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.chippergrpc2.IntentGraphResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chippergrpc2.IntentGraphResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    session: jspb.Message.getFieldWithDefault(msg, 1, ""),
    deviceId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    responseType: jspb.Message.getFieldWithDefault(msg, 3, 0),
    isFinal: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    intentResult: (f = msg.getIntentResult()) && proto.chippergrpc2.IntentResult.toObject(includeInstance, f),
    speechResult: (f = msg.getSpeechResult()) && proto.chippergrpc2.SpeechResult.toObject(includeInstance, f),
    mode: jspb.Message.getFieldWithDefault(msg, 7, 0),
    queryText: jspb.Message.getFieldWithDefault(msg, 8, ""),
    spokenText: jspb.Message.getFieldWithDefault(msg, 9, ""),
    commandType: jspb.Message.getFieldWithDefault(msg, 10, ""),
    domainsUsedList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    audioId: jspb.Message.getFieldWithDefault(msg, 12, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.chippergrpc2.IntentGraphResponse}
 */
proto.chippergrpc2.IntentGraphResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.chippergrpc2.IntentGraphResponse;
  return proto.chippergrpc2.IntentGraphResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.chippergrpc2.IntentGraphResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.chippergrpc2.IntentGraphResponse}
 */
proto.chippergrpc2.IntentGraphResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSession(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceId(value);
      break;
    case 3:
      var value = /** @type {!proto.chippergrpc2.IntentGraphMode} */ (reader.readEnum());
      msg.setResponseType(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsFinal(value);
      break;
    case 5:
      var value = new proto.chippergrpc2.IntentResult;
      reader.readMessage(value,proto.chippergrpc2.IntentResult.deserializeBinaryFromReader);
      msg.setIntentResult(value);
      break;
    case 6:
      var value = new proto.chippergrpc2.SpeechResult;
      reader.readMessage(value,proto.chippergrpc2.SpeechResult.deserializeBinaryFromReader);
      msg.setSpeechResult(value);
      break;
    case 7:
      var value = /** @type {!proto.chippergrpc2.RobotMode} */ (reader.readEnum());
      msg.setMode(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setQueryText(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setSpokenText(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setCommandType(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addDomainsUsed(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setAudioId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.chippergrpc2.IntentGraphResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.chippergrpc2.IntentGraphResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chippergrpc2.IntentGraphResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSession();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDeviceId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getResponseType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getIsFinal();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getIntentResult();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.chippergrpc2.IntentResult.serializeBinaryToWriter
    );
  }
  f = message.getSpeechResult();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.chippergrpc2.SpeechResult.serializeBinaryToWriter
    );
  }
  f = message.getMode();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getQueryText();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getSpokenText();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getCommandType();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getDomainsUsedList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
  f = message.getAudioId();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
};


/**
 * optional string session = 1;
 * @return {string}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.getSession = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
 */
proto.chippergrpc2.IntentGraphResponse.prototype.setSession = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string device_id = 2;
 * @return {string}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.getDeviceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
 */
proto.chippergrpc2.IntentGraphResponse.prototype.setDeviceId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional IntentGraphMode response_type = 3;
 * @return {!proto.chippergrpc2.IntentGraphMode}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.getResponseType = function() {
  return /** @type {!proto.chippergrpc2.IntentGraphMode} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.chippergrpc2.IntentGraphMode} value
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
 */
proto.chippergrpc2.IntentGraphResponse.prototype.setResponseType = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional bool is_final = 4;
 * @return {boolean}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.getIsFinal = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
 */
proto.chippergrpc2.IntentGraphResponse.prototype.setIsFinal = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional IntentResult intent_result = 5;
 * @return {?proto.chippergrpc2.IntentResult}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.getIntentResult = function() {
  return /** @type{?proto.chippergrpc2.IntentResult} */ (
    jspb.Message.getWrapperField(this, proto.chippergrpc2.IntentResult, 5));
};


/**
 * @param {?proto.chippergrpc2.IntentResult|undefined} value
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
*/
proto.chippergrpc2.IntentGraphResponse.prototype.setIntentResult = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
 */
proto.chippergrpc2.IntentGraphResponse.prototype.clearIntentResult = function() {
  return this.setIntentResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.hasIntentResult = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional SpeechResult speech_result = 6;
 * @return {?proto.chippergrpc2.SpeechResult}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.getSpeechResult = function() {
  return /** @type{?proto.chippergrpc2.SpeechResult} */ (
    jspb.Message.getWrapperField(this, proto.chippergrpc2.SpeechResult, 6));
};


/**
 * @param {?proto.chippergrpc2.SpeechResult|undefined} value
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
*/
proto.chippergrpc2.IntentGraphResponse.prototype.setSpeechResult = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
 */
proto.chippergrpc2.IntentGraphResponse.prototype.clearSpeechResult = function() {
  return this.setSpeechResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.hasSpeechResult = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional RobotMode mode = 7;
 * @return {!proto.chippergrpc2.RobotMode}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.getMode = function() {
  return /** @type {!proto.chippergrpc2.RobotMode} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.chippergrpc2.RobotMode} value
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
 */
proto.chippergrpc2.IntentGraphResponse.prototype.setMode = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional string query_text = 8;
 * @return {string}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.getQueryText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
 */
proto.chippergrpc2.IntentGraphResponse.prototype.setQueryText = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string spoken_text = 9;
 * @return {string}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.getSpokenText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
 */
proto.chippergrpc2.IntentGraphResponse.prototype.setSpokenText = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string command_type = 10;
 * @return {string}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.getCommandType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
 */
proto.chippergrpc2.IntentGraphResponse.prototype.setCommandType = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * repeated string domains_used = 11;
 * @return {!Array<string>}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.getDomainsUsedList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
 */
proto.chippergrpc2.IntentGraphResponse.prototype.setDomainsUsedList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
 */
proto.chippergrpc2.IntentGraphResponse.prototype.addDomainsUsed = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
 */
proto.chippergrpc2.IntentGraphResponse.prototype.clearDomainsUsedList = function() {
  return this.setDomainsUsedList([]);
};


/**
 * optional string audio_id = 12;
 * @return {string}
 */
proto.chippergrpc2.IntentGraphResponse.prototype.getAudioId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.chippergrpc2.IntentGraphResponse} returns this
 */
proto.chippergrpc2.IntentGraphResponse.prototype.setAudioId = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


