// source: chipperpb.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.chippergrpc2.TextRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.chippergrpc2.IntentService');
goog.forwardDeclare('proto.chippergrpc2.LanguageCode');
goog.forwardDeclare('proto.chippergrpc2.RobotMode');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.chippergrpc2.TextRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.chippergrpc2.TextRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.chippergrpc2.TextRequest.displayName = 'proto.chippergrpc2.TextRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.chippergrpc2.TextRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.chippergrpc2.TextRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.chippergrpc2.TextRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chippergrpc2.TextRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    session: jspb.Message.getFieldWithDefault(msg, 1, ""),
    deviceId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    textInput: jspb.Message.getFieldWithDefault(msg, 3, ""),
    languageCode: jspb.Message.getFieldWithDefault(msg, 4, 0),
    intentService: jspb.Message.getFieldWithDefault(msg, 5, 0),
    firmwareVersion: jspb.Message.getFieldWithDefault(msg, 6, ""),
    mode: jspb.Message.getFieldWithDefault(msg, 7, 0),
    skipDas: jspb.Message.getBooleanFieldWithDefault(msg, 8, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.chippergrpc2.TextRequest}
 */
proto.chippergrpc2.TextRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.chippergrpc2.TextRequest;
  return proto.chippergrpc2.TextRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.chippergrpc2.TextRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.chippergrpc2.TextRequest}
 */
proto.chippergrpc2.TextRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSession(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTextInput(value);
      break;
    case 4:
      var value = /** @type {!proto.chippergrpc2.LanguageCode} */ (reader.readEnum());
      msg.setLanguageCode(value);
      break;
    case 5:
      var value = /** @type {!proto.chippergrpc2.IntentService} */ (reader.readEnum());
      msg.setIntentService(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setFirmwareVersion(value);
      break;
    case 7:
      var value = /** @type {!proto.chippergrpc2.RobotMode} */ (reader.readEnum());
      msg.setMode(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSkipDas(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.chippergrpc2.TextRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.chippergrpc2.TextRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.chippergrpc2.TextRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chippergrpc2.TextRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSession();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDeviceId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTextInput();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLanguageCode();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getIntentService();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getFirmwareVersion();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getMode();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getSkipDas();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
};


/**
 * optional string session = 1;
 * @return {string}
 */
proto.chippergrpc2.TextRequest.prototype.getSession = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.chippergrpc2.TextRequest} returns this
 */
proto.chippergrpc2.TextRequest.prototype.setSession = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string device_id = 2;
 * @return {string}
 */
proto.chippergrpc2.TextRequest.prototype.getDeviceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.chippergrpc2.TextRequest} returns this
 */
proto.chippergrpc2.TextRequest.prototype.setDeviceId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string text_input = 3;
 * @return {string}
 */
proto.chippergrpc2.TextRequest.prototype.getTextInput = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.chippergrpc2.TextRequest} returns this
 */
proto.chippergrpc2.TextRequest.prototype.setTextInput = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional LanguageCode language_code = 4;
 * @return {!proto.chippergrpc2.LanguageCode}
 */
proto.chippergrpc2.TextRequest.prototype.getLanguageCode = function() {
  return /** @type {!proto.chippergrpc2.LanguageCode} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.chippergrpc2.LanguageCode} value
 * @return {!proto.chippergrpc2.TextRequest} returns this
 */
proto.chippergrpc2.TextRequest.prototype.setLanguageCode = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional IntentService intent_service = 5;
 * @return {!proto.chippergrpc2.IntentService}
 */
proto.chippergrpc2.TextRequest.prototype.getIntentService = function() {
  return /** @type {!proto.chippergrpc2.IntentService} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.chippergrpc2.IntentService} value
 * @return {!proto.chippergrpc2.TextRequest} returns this
 */
proto.chippergrpc2.TextRequest.prototype.setIntentService = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional string firmware_version = 6;
 * @return {string}
 */
proto.chippergrpc2.TextRequest.prototype.getFirmwareVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.chippergrpc2.TextRequest} returns this
 */
proto.chippergrpc2.TextRequest.prototype.setFirmwareVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional RobotMode mode = 7;
 * @return {!proto.chippergrpc2.RobotMode}
 */
proto.chippergrpc2.TextRequest.prototype.getMode = function() {
  return /** @type {!proto.chippergrpc2.RobotMode} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.chippergrpc2.RobotMode} value
 * @return {!proto.chippergrpc2.TextRequest} returns this
 */
proto.chippergrpc2.TextRequest.prototype.setMode = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional bool skip_das = 8;
 * @return {boolean}
 */
proto.chippergrpc2.TextRequest.prototype.getSkipDas = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.chippergrpc2.TextRequest} returns this
 */
proto.chippergrpc2.TextRequest.prototype.setSkipDas = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


