// source: token.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.tokenpb.AssociatePrimaryUserRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tokenpb.AssociatePrimaryUserRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tokenpb.AssociatePrimaryUserRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tokenpb.AssociatePrimaryUserRequest.displayName = 'proto.tokenpb.AssociatePrimaryUserRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.tokenpb.AssociatePrimaryUserRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tokenpb.AssociatePrimaryUserRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tokenpb.AssociatePrimaryUserRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    generateStsToken: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    sessionCertificate: msg.getSessionCertificate_asB64(),
    clientName: jspb.Message.getFieldWithDefault(msg, 5, ""),
    appId: jspb.Message.getFieldWithDefault(msg, 6, ""),
    skipClientToken: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    revokeClientTokens: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    expirationMinutes: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tokenpb.AssociatePrimaryUserRequest}
 */
proto.tokenpb.AssociatePrimaryUserRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tokenpb.AssociatePrimaryUserRequest;
  return proto.tokenpb.AssociatePrimaryUserRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tokenpb.AssociatePrimaryUserRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tokenpb.AssociatePrimaryUserRequest}
 */
proto.tokenpb.AssociatePrimaryUserRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGenerateStsToken(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSessionCertificate(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientName(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppId(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSkipClientToken(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRevokeClientTokens(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setExpirationMinutes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tokenpb.AssociatePrimaryUserRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tokenpb.AssociatePrimaryUserRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tokenpb.AssociatePrimaryUserRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGenerateStsToken();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getSessionCertificate_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getClientName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAppId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getSkipClientToken();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getRevokeClientTokens();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getExpirationMinutes();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
};


/**
 * optional bool generate_sts_token = 3;
 * @return {boolean}
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.getGenerateStsToken = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.tokenpb.AssociatePrimaryUserRequest} returns this
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.setGenerateStsToken = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bytes session_certificate = 4;
 * @return {string}
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.getSessionCertificate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes session_certificate = 4;
 * This is a type-conversion wrapper around `getSessionCertificate()`
 * @return {string}
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.getSessionCertificate_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSessionCertificate()));
};


/**
 * optional bytes session_certificate = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSessionCertificate()`
 * @return {!Uint8Array}
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.getSessionCertificate_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSessionCertificate()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.tokenpb.AssociatePrimaryUserRequest} returns this
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.setSessionCertificate = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional string client_name = 5;
 * @return {string}
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.getClientName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.tokenpb.AssociatePrimaryUserRequest} returns this
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.setClientName = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string app_id = 6;
 * @return {string}
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.getAppId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.tokenpb.AssociatePrimaryUserRequest} returns this
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.setAppId = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional bool skip_client_token = 7;
 * @return {boolean}
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.getSkipClientToken = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.tokenpb.AssociatePrimaryUserRequest} returns this
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.setSkipClientToken = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool revoke_client_tokens = 8;
 * @return {boolean}
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.getRevokeClientTokens = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.tokenpb.AssociatePrimaryUserRequest} returns this
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.setRevokeClientTokens = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional uint32 expiration_minutes = 9;
 * @return {number}
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.getExpirationMinutes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.tokenpb.AssociatePrimaryUserRequest} returns this
 */
proto.tokenpb.AssociatePrimaryUserRequest.prototype.setExpirationMinutes = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


